export const authconstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",

    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

    SIGHNUP_REQUEST: "SIGHNUP_REQUEST",
    SIGHNUP_SUCCESS: "SIGHNUP_SUCCESS",
    SIGHNUP_FAILURE: "SIGHNUP_FAILURE",

    ISMENUBAR_OPEN: "ISMENUBAR_OPEN",

    USERLIST_REQUEST: "USERLIST_REQUEST",
    USERLIST_SUCCESS: "USERLIST_SUCCESS",
    USERLIST_FAILURE: "USERLIST_FAILURE",

    ADDUSER_REQUEST: "ADDUSER_REQUEST",
    ADDUSER_SUCCESS: "ADDUSER_SUCCESS",
    ADDUSER_FAILURE: "ADDUSER_FAILURE",

    FILEUPLOAD_REQUEST: "FILEUPLOAD_REQUEST",
    FILEUPLOAD_SUCCESS: "FILEUPLOAD_SUCCESS",
    FILEUPLOAD_FAILURE: "FILEUPLOAD_FAILURE",

    SUCCESS_ALERT: "SUCCESS_ALERT",
    ERROR_ALERT: "ERROR_ALERT",
}
export const categoryConstants = {
    ADDCATEGORY_REQUEST: "ADDCATEGORY_REQUEST",
    ADDCATEGORY_SUCCESS: "ADDCATEGORY_SUCCESS",
    ADDCATEGORY_FAILURE: "ADDCATEGORY_FAILURE",

    CATEGORYLIST_REQUEST: "CATEGORYLIST_REQUEST",
    CATEGORYLIST_SUCCESS: "CATEGORYLIST_SUCCESS",
    CATEGORYLIST_FAILURE: "CATEGORYLIST_FAILURE",

    CATEGORYALLLIST_REQUEST: "CATEGORYALLLIST_REQUEST",
    CATEGORYALLLIST_SUCCESS: "CATEGORYALLLIST_SUCCESS",
    CATEGORYALLLIST_FAILURE: "CATEGORYALLLIST_FAILURE",
}
export const imageConstants = {
    IMAGELIS_REQUEST: "IMAGELIS_REQUEST",
    IMAGELIST_SUCCESS: "IMAGELIST_SUCCESS",
}

export const optionConstants = {
    ADDOPTIONS_REQUEST: "ADDOPTIONS_REQUEST",
    ADDOPTIONS_SUCCESS: "ADDOPTIONS_SUCCESS",
    ADDOPTIONS_FAILURE: "ADDOPTIONS_FAILURE",

    OPTIONSLIST_REQUEST: "OPTIONSLIST_REQUEST",
    OPTIONSLIST_SUCCESS: "OPTIONSLIST_SUCCESS",
    OPTIONSLIST_FAILURE: "OPTIONSLIST_FAILURE",
}

export const productconstants = {
    PRODUCTLIST_REQUEST: "PRODUCTLIST_REQUEST",
    PRODUCTLIST_SUCCESS: "PRODUCTLIST_SUCCESS",
    PRODUCTLIST_FAILURE: "PRODUCTLIST_FAILURE",

    PRODUCTADD_REQUEST: "PRODUCTADD_REQUEST",
    PRODUCTADD_SUCCESS: "PRODUCTADD_SUCCESS",
    PRODUCTADD_FAILURE: "PRODUCTADD_FAILURE",

    PRODUCTLISTHOME_REQUEST: "PRODUCTLISTHOME_REQUEST",
    PRODUCTLISTHOME_SUCCESS: "PRODUCTLISTHOME_SUCCESS",
    PRODUCTLISTHOME_FAILURE: "PRODUCTLISTHOME_FAILURE",

    PRODUCTLISTHOMEADD_REQUEST: "PRODUCTLISTHOMEADD_REQUEST",
    PRODUCTLISTHOMEADDSUCCESS: "PRODUCTLISTHOMEADDSUCCESS",
    PRODUCTLISTHOMEADD_FAILURE: "PRODUCTLISTHOMEADD_FAILURE",

    VARIENTLIST_REQUEST: "VARIENTLIST_REQUEST",
    VARIENTLIST_SUCCESS: "VARIENTLIST_SUCCESS",
    VARIENTLIST_FAILURE: "VARIENTLIST_FAILURE",


}

export const product_attributeconstant = {
    PRODUCT_ATTRIBUTE_ADDREQUEST: "PRODUCT_ATTRIBUTE_ADDREQUEST",
    PRODUCT_ATTRIBUTE_ADDSUCCESS: "PRODUCT_ATTRIBUTE_ADDSUCCESS",
    PRODUCT_ATTRIBUTE_ADDFAILURE: "PRODUCT_ATTRIBUTE_ADDFAILURE",

    PRODUCT_ATTRIBUTE_LISTREQUEST: "PRODUCT_ATTRIBUTE_LISTREQUEST",
    PRODUCT_ATTRIBUTE_LISTSUCCESS: "PRODUCT_ATTRIBUTE_LISTSUCCESS",
    PRODUCT_ATTRIBUTE_LISTFAILURE: "PRODUCT_ATTRIBUTE_LISTFAILURE",
}
export const brandconstant = {
    BRANDLIST_REQUEST: "BRANDLIST_REQUEST",
    BRANDLIST_SUCCESS: "BRANDLIST_SUCCESS",
    BRANDLIST_FAILURE: "BRANDLIST_FAILURE",

    ADDBRAND_REQUEST: "ADDBRAND_REQUEST",
    ADDBRAND_SUCCESS: "ADDBRAND_SUCCESS",
    ADDBRAND_FAILURE: "ADDBRAND_FAILURE",
}

export const offerconstants = {
    OFFERLIST_REQUEST: "OFFERLIST_REQUEST",
    OFFERLIST_SUCCESS: "OFFERLIST_SUCCESS",
    OFFERLIST_FAILURE: "OFFERLIST_FAILURE",

    ADDOFFER_REQUEST: "ADDOFFER_REQUEST",
    ADDOFFER_SUCCESS: "ADDOFFER_SUCCESS",
    ADDOFFER_FAILURE: "ADDOFFER_FAILURE",

    OFFERITEMlIST_REQUEST: "OFFERITEMlIST_REQUEST",
    OFFERITEMlIST_SUCCESS: "OFFERITEMlIST_SUCCESS",
    OFFERITEMlIST_FAILURE: "OFFERITEMlIST_FAILURE",

    ADDOFFERITEM_REQUEST: "ADDOFFERITEM_REQUEST",
    ADDOFFERITEM_SUCCESS: "ADDOFFERITEM_SUCCESS",
    ADDOFFERITEM_FAILURE: "ADDOFFERITEM_FAILURE",
}

export const orderConstants = {
    ORDER_REQUEST: "ORDER_REQUEST",
    ORDER_SUCCESS: "ORDER_SUCCESS",
    ORDER_FAIL: "ORDER_FAIL",
}